export { parseAttributionUrl, readQuery, referrerHostOf } from './parse.js';
export { mergeAttributionTouch, extractClickIds, emptyAttribution, stampVersions } from './merge.js';
export { sanitizeField, normalizeHost, hostMatches, areRelatedHosts } from './sanitize.js';
export { resolveChannelLabel, CHANNEL_LABELS, CHANNEL_LABELS_VERSION } from './knowledge.js';
export type { ChannelLabelInput } from './knowledge.js';
export { SEARCH_REFERRER_RULES, SOCIAL_REFERRER_RULES } from './knowledge.js';
export type { ReferrerRule } from './knowledge.js';
export { DIAGNOSTIC_CODES, nullDiagnosticSink } from './diagnostics.js';
export type { Diagnostic, DiagnosticLevel, DiagnosticSink } from './diagnostics.js';
export type { AttributionPayload, AttributionTouch, ParseAttributionInput, ParseResult, ParsedTouch } from './types.js';
