/**
 * Pure file generators for the ClickTrail sv add-on.
 *
 * Every function is (answers) -> string so tests can assert generated file
 * content without touching a filesystem.
 */
import type { AddonAnswers } from './types.js';

export const DEFAULT_SITE_ID_PLACEHOLDER = 'CLICKTRAIL_SITE_ID';

function siteIdOr(answers: AddonAnswers, fallback: string): string {
  const value = answers['siteId'];
  return value && value.trim() !== '' ? value.trim() : fallback;
}

/** src/hooks.server.ts — the ClickTrail attribution handle. */
export function generateHooksServer(answers: AddonAnswers = {}): string {
  return `// Generated by @vizuh/clicktrail-sv (EXPERIMENTAL).
// First-party attribution capture for every request.
import { clicktrail } from '@vizuh/clicktrail-sveltekit';

const siteId = process.env.CLICKTRAIL_SITE_ID ?? '${siteIdOr(answers, 'your-site-id')}';

export const handle = clicktrail({
  siteId,
  // Optional first-party proxy: forward events to your collector without
  // exposing visitor IPs. Set CLICKTRAIL_UPSTREAM to enable.
  ...(process.env.CLICKTRAIL_UPSTREAM
    ? { proxy: { upstream: process.env.CLICKTRAIL_UPSTREAM } }
    : {}),
});
`;
}

/** src/routes/+layout.svelte — root layout browser boot. */
export function generateRootLayout(): string {
  return `<!-- Generated by @vizuh/clicktrail-sv (EXPERIMENTAL). -->
<script lang="ts">
  import ClickTrail from '@vizuh/clicktrail-sveltekit/ClickTrail.svelte';
</script>

<ClickTrail />
`;
}

/** .env addition — CLICKTRAIL_SITE_ID placeholder. */
export function generateEnv(answers: AddonAnswers = {}): string {
  return `# Added by @vizuh/clicktrail-sv (EXPERIMENTAL)
# Your ClickTrail site identifier (from your ClickTrail workspace).
CLICKTRAIL_SITE_ID=${siteIdOr(answers, 'your-site-id')}

# Optional: enable the first-party proxy in hooks.server.ts.
# CLICKTRAIL_UPSTREAM=https://collector.example.com/v1/events
`;
}

/** Example conversion endpoint calling trackConversion server-side. */
export function generateConversionEndpoint(answers: AddonAnswers = {}): string {
  return `// Generated by @vizuh/clicktrail-sv (EXPERIMENTAL).
// Example server-side conversion endpoint.
// POST /api/clicktrail-example -> tracks a lead conversion for this visitor.
import { json } from '@sveltejs/kit';
import { trackConversion } from '@vizuh/clicktrail-sveltekit/server';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ request }) => {
  const result = await trackConversion(request, {
    event: 'lead',
    endpoint: process.env.CLICKTRAIL_COLLECTOR_URL ?? 'https://collector.example.com/v1/events',
    siteId: process.env.CLICKTRAIL_SITE_ID ?? '${siteIdOr(answers, 'your-site-id')}',
  });
  // result never throws into request handling; it resolves { ok, status }.
  return json({ tracked: result.ok, status: result.status });
};
`;
}
