/**
 * Idempotent event-id helpers.
 *
 * Contract: event_id is minted ONCE at enqueue, persisted with the payload,
 * reused verbatim across retries, and never regenerated by platforms.
 * Collectors treat duplicate ids inside the retention window as success-no-op.
 */
import { uuidV4FromBytes } from './core/uuid.js';


/** Byte source contract (caller-owned randomness; frozen-core rule). */
export type RandomBytesFn = (byteLength: number) => Uint8Array;

/** Mint a fresh streaming-style event id (`evt_<uuid>`); randomness is injected (frozen-core rule). */
export function mintEventId(randomBytes: RandomBytesFn): string {
  return `evt_${uuidV4FromBytes(randomBytes(16))}`;
}

function fnv1a32(input: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

/**
 * Derive a STABLE event id from a site-scoped external key so server replays
 * (webhook redelivery, double booking callback) reuse the same id without
 * remembering anything: deriveStableEventId('s1','bk_9:completed') is pure.
 */
export function deriveStableEventId(siteId: string, externalKey: string): string {
  if (!siteId || !externalKey) {
    throw new TypeError('deriveStableEventId requires non-empty siteId and externalKey.');
  }
  const digest = fnv1a32(`${siteId}\u0000${externalKey}`).toString(16).padStart(8, '0');
  return `evt_s-${digest}`;
}
