"""Idempotent event-id helpers (mirrors packages/core/src/ids.ts).

Contract: event_id is minted ONCE at enqueue, persisted with the payload,
reused verbatim across retries, and never regenerated by platforms.
Collectors treat duplicate ids inside the retention window as success-no-op.
"""

import hashlib
import uuid
from typing import Callable, Optional

RandomBytesFn = Callable[[int], bytes]


def _uuid_v4_from_bytes(raw: bytes) -> str:
    """Format 16 caller-provided bytes as a UUID v4 string (JS parity)."""
    if len(raw) < 16:
        raise ValueError("need at least 16 bytes")
    b = bytearray(raw[:16])
    b[6] = (b[6] & 0x0F) | 0x40  # version 4
    b[8] = (b[8] & 0x3F) | 0x80  # RFC 4122 variant
    hexs = b.hex()
    return "-".join((hexs[0:8], hexs[8:12], hexs[12:16], hexs[16:20], hexs[20:32]))


def mint_event_id(random_bytes: Optional[RandomBytesFn] = None) -> str:
    """Mint a fresh streaming-style event id (``evt_<uuid4>``).

    Randomness is injected (``random_bytes(n) -> bytes``); the default source
    is ``os.urandom``. Callers mint ONCE per logical occurrence.
    """
    src = random_bytes if random_bytes is not None else _default_random_bytes
    return "evt_" + _uuid_v4_from_bytes(src(16))


def _default_random_bytes(byte_length: int) -> bytes:
    import os

    return os.urandom(byte_length)


def derive_stable_event_id(site_id: str, external_key: str) -> str:
    """Derive a STABLE event id from a site-scoped external key.

    Server replays (webhook redelivery, double booking callback) reuse the
    same id without remembering anything: pure function of the pair, mirroring
    the JS core's ``deriveStableEventId`` bit for bit.
    """
    if not isinstance(site_id, str) or not site_id or not isinstance(external_key, str) or not external_key:
        raise TypeError("derive_stable_event_id requires non-empty siteId and externalKey.")
    message = (site_id + "\u0000" + external_key).encode("utf-8")
    digest = hashlib.sha256(message).hexdigest()[:32]
    return "evt_s-" + digest
